var D2R_namespacePrefixes = {
    "jps": "https://jpsearch.go.jp/term/property#",
    "schema": "http://schema.org/",
    "type": "https://jpsearch.go.jp/term/type/",
    "chname": "https://jpsearch.go.jp/entity/chname/",
    "place": "https://jpsearch.go.jp/entity/place/",
    "time": "https://jpsearch.go.jp/entity/time/",
    "work": "https://jpsearch.go.jp/entity/work/",
    "role": "https://jpsearch.go.jp/term/role/",
    "keyword": "https://jpsearch.go.jp/term/keyword/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "gvname": "https://jpsearch.go.jp/entity/gvname/",
    "ncname": "https://jpsearch.go.jp/entity/ncname/",
    "ncplace": "https://jpsearch.go.jp/entity/ncplace/",
    "series": "https://jpsearch.go.jp/entity/series/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
    owl: 'http://www.w3.org/2002/07/owl#',
    "jp-textbook": "https://w3id.org/jp-textbook/",
    "jp-cos": "https://w3id.org/jp-cos/",
};

